version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    gitversion /output buildserver

    where msbuild

    nuget restore
build:
  project: PrimS.Telnet.sln
  verbosity: minimal
