version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: >-
    gitversion /output buildserver

    nuget restore
build:
  project: PrimS.Telnet.sln
  verbosity: quiet
after_build:
- ps: nuget pack Telnet.nuspec -Version $env:GitVersion_MajorMinorPatch
artifacts:
- path: Telnet.*.nupkg